<div class="mainNav">
   <div align="center" style="margin-top:10px;color:white;font-weight:bold;font-size: 13px;">Output Library</div>
   <!-- Main nav -->     
   <ul class="nav">
      <li><a href="<?php echo base_url();?>folder/my-folder" class="active"><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>My Folder</span></a></li>
      <li><a <?php if(/*$is_paid*/1==1){ ?> href="<?php echo base_url();?>folder/team-folder" class="active" <?php } else {?> id="32" data-icon="&#xe090;" class="dialog_open_pro fs1 active" <?php } ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Team Folder</span></a></li>
      <li><a href="<?php echo base_url();?>folder/campaign-kits" class="active" ><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Campaign Kits</span></a></li>
      <li><a <?php //if($class['step1'] AND $class['step2'] AND $class['step3'] AND $class['step4'] AND $class['step5'] AND $class['step6'] AND $class['step7'] == 'Active'){ ?> href="<?php echo base_url();?>folder/sales-scripts" class="active" <?php //} ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Sales Scripts</span></a></li>
      <li><a href="<?php echo base_url();?>folder/email-templates" class="active" ><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Emails and Letters</span></a></li>
      <li><a  href="<?php echo base_url();?>folder/voicemail-script" class="active"><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Voicemail Script</span></a></li>
      <li><a href="<?php echo base_url();?>folder/responses-questions" class="active"><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Responses and Questions</span></a></li>
      <li><a <?php //if($class['step3'] == 'Active'){ ?> href="<?php echo base_url();?>folder/ideal-prospect-profile"  class="active" <?php // } ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Ideal Prospect</span></a></li>
      <li><a href="<?php echo base_url();?>folder/marketing-output" class="active"><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Marketing Output</span></a></li>
      <!--  <li><a <?php //if($class['step1'] AND $class['step3'] == 'Active'){ ?> href="<?php echo base_url();?>folder/elevator-pitch" class="active" <?php //} ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Powerful Statements</span></a></li> -->         <!-- <li><a <?php //if($class['step2'] == 'Active'){ ?>  href="<?php echo base_url();?>folder/prospect-pain-points" class="active" <?php //} ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Prospect Pain Points</span></a></li> -->                  <!-- <li><a <?php //if($class['step4'] == 'Active'){ ?> href="<?php echo base_url();?>folder/qualifying-questions"  class="active" <?php //} ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Sales Questions</span></a></li> -->         <!-- <li><a <?php if($is_paid){ ?> href="<?php echo base_url();?>folder/building-interest" class="active" <?php } else {?> id="32" data-icon="&#xe090;" class="dialog_open_pro fs1 active" <?php } ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Building Interest Silver Bullets</span></a></li> -->         <!-- <li><a <?php //if($class['step1'] == 'Active' AND $class['step2'] == 'Active' AND $class['step4'] == 'Active' AND $class['step8'] == 'Active'){ ?> href="<?php echo base_url();?>folder/objections-map" class="active" <?php //} ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Objections Map</span></a></li>  -->                                                                                                                                                                                                                                                                                                                                                                                          			<!-- <li><a <?php if($is_paid){ ?> href="<?php echo base_url();?>folder/name-drop-statments" class="active" <?php } else {?> id="32" data-icon="&#xe090;" class="dialog_open_pro fs1 active" <?php } ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Name Drop Statement</span></a></li> -->		<!-- <li><a <?php if($is_paid){ ?> href="<?php echo base_url();?>folder/closing-questions" class="active" <?php } else {?> id="32" data-icon="&#xe090;" class="dialog_open_pro fs1 active" <?php } ?>><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Closing Questions</span></a></li> -->		<!--  <li><a href="<?php echo base_url();?>folder/sales-presentation" class="active"><span style="font-size: 20px;" class="iconb" data-icon="&#xe015;"></span><span>Sales Presentation</span></a></li> -->		      
   </ul>
</div>